language: node_js
node_js:
  - "6"
before install:
  - sudo apt-get update -y
install: true
  - npm install
script:
  - ssh-keygen -R $SSH_IP
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
